### ISSUE TITLE
OperationalError when loading NetGen

### ISSUE THREAD

**Issue by JenkeScheen** [GPCR-ModSim/qfepweb#18]
currently on Main, launching the webserver, selecting Netgen and loading https://github.com/GPCR-ModSim/qfepweb/blob/multifile_upload/networkgen/test_files/CDK2_ligands.sdf fails when selecting `Submit` (with any metric):

<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">OperationalError at /netgen/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">no such table: networkgen_generator</pre>

Request Method: | POST
-- | --
http://127.0.0.1:8000/netgen/
3.2.6
OperationalError
no such table: networkgen_generator
/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py, line 423, in execute
/Users/jscheen/projects/modsim/qfepweb/bin/python
3.7.7
['/Users/jscheen/projects/modsim/qfepweb/bin',  '/Users/jscheen/projects/modsim/qfepweb/qfepweb',  '/Users/jscheen/miniconda3/envs/mbp/lib/python37.zip',  '/Users/jscheen/miniconda3/envs/mbp/lib/python3.7',  '/Users/jscheen/miniconda3/envs/mbp/lib/python3.7/lib-dynload',  '/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages']
Tue, 10 Aug 2021 11:57:50 +0000

traceback:
```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/netgen/

Django Version: 3.2.6
Python Version: 3.7.7
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'debug_toolbar',
 'crispy_forms',
 'about',
 'common',
 'home',
 'networkgen',
 'runner',
 'utils']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (no such table: networkgen_generator) was the direct cause of the following exception:
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/views/generic/edit.py", line 125, in form_valid
    self.object = form.save()
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/forms/models.py", line 468, in save
    self.instance.save()
  File "/Users/jscheen/projects/modsim/qfepweb/qfepweb/networkgen/models.py", line 109, in save
    result = super().save(*args, **kwargs)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django_extensions/db/models.py", line 22, in save
    super().save(**kwargs)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/models/base.py", line 727, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/models/base.py", line 765, in save_base
    force_update, using, update_fields,
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw,
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 133, in _record
    return method(sql, params)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /netgen/
Exception Value: no such table: networkgen_generator
```

**Comment by xbello** [comment]
Can you verify that running "python manage.py migrate" answers "No migrations to apply"?

**Comment by JenkeScheen** [comment]
ah, my bad. I'd not done those migrations thinking they weren't necessary; turns out they are. Working fine now.
