### ISSUE TITLE
launching issues

### ISSUE THREAD

**Issue by JenkeScheen** [GPCR-ModSim/qfepweb#22]
I'm having launching issues again, both on `main` and on `cluster_config` branches. After going through the prescribed steps, running `django-admin runserver` throws:
```
(qfepweb) (mbp) jscheen@macbook:$ django-admin run-server
Traceback (most recent call last):
  File "/Users/jscheen/projects/modsim/qfepweb/bin/django-admin", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/jscheen/projects/modsim/qfepweb/lib/python3.7/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/jscheen/miniconda3/envs/mbp/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jscheen/projects/modsim/qfepweb/qfepweb/networkgen/models.py", line 12, in <module>
    from networkgen import mapgen
  File "/Users/jscheen/projects/modsim/qfepweb/qfepweb/networkgen/mapgen.py", line 3, in <module>
    from functools import cached_property, lru_cache
ImportError: cannot import name 'cached_property' from 'functools' (/Users/jscheen/miniconda3/envs/mbp/lib/python3.7/functools.py)
```

The same exception is thrown when calling `python manage.py migrate`.

**Comment by xbello** [comment]
`cached_property` is new in Python 3.8. We can get rid of it taking a small hit in performance now if you cannot upgrade from Python 3.7 to at least Python 3.8 (3.9 recommended).

**Comment by JenkeScheen** [comment]
thanks!
